version: "3.8"

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: jacoblincool/gdg-on-campus-ntnu-bot
    container_name: gdg-on-campus-ntnu-bot
    restart: unless-stopped
    env_file:
      - .env
